### PR TITLE
nav bar improved

### PR DESCRIPTION
**Pull request by mansisharma31**
I have added the background color in navigation bar and did some modifications in its width and padding.

### CODE REVIEW

**Comment by Guneetsinghtuli** [comment]
It would be really helpful if you could attach a screenshot for reference.

**Comment by mansisharma31** [comment]
Screenshot (208)

**Comment by Guneetsinghtuli** [comment]
Great work @mansisharma31, But since we have updated the design we are looking for the navbar to look similar, We would appreciate it if you could create another PR with the updated Navbar

**Comment by A1Kumari** [comment]
Can you please assign this issue to me.
I am already working on the home section so with that I will also change this

**Pull request closed without merging**
