### PR TITLE
Navbar and footer Updated and modified

### PR DESCRIPTION
**Pull request by Murtaza-Farooqui**
Merge this under hacktoberfest2022

### CODE REVIEW

**Comment by Murtaza-Farooqui** [comment]
Accept this Pull request. designed navbar and footer added good effects

**Comment by Murtaza-Farooqui** [comment]
Added hover effect in navbar and improved it.
@GDSC-adgitm 
@Guneetsinghtuli 
Screenshot (3)

**Comment by Guneetsinghtuli** [comment]
Great work, But since we have updated the design in the Figma, It would be better to have something similar to that

**Comment by Murtaza-Farooqui** [comment]
Is there any other issue that I can fix @Guneetsinghtuli

**Pull request closed without merging**
